default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: checkallergy
  password: checkallergy


development:
  <<: *default
  database: checkallergy_development
  pool: 5
  host: localhost
  username: checkallergy
  password: checkallergy

test:
  <<: *default
  database: checkallergy_test
