User.create!([
  {email: "michau@gmail.com", password: "olekszy", password_confirmation: "olekszy", pesel: "91071313315", birth_date: "2017-02-11", admin: true}
])
Allergen.create!([
  {name: "jaja kurze", description: "Alergia na jajka (w szczególności na białko jaja kurzego) jest rodzajem alergii pokarmowej występuje przede wszystkim u dzieci, jednak zdarza się również u dorosłych. Do najczęstszych objawów należy katar, nudności, biegunka, bóle brzucha, swędząca wysypka, bóle głowy. Najgroźniejszym objawem jest wstrząs anafilaktyczny. Najskuteczniejszym sposobem leczenia jest zastosowanie diety eliminacyjnej. Wbrew pozorom nie jest to jednak proste rozwiązanie. Dla osoby uczulonej zagrożenie stwarza nie tylko zjedzenie samego jajka, ale także produktów, które zawierają je nawet w śladowych ilościach. Jajka znajdują się w wielu artykułach spożywczych – naleśnikach, lodach, makaronach, pierogach, pasztetach itd. Uczulenie na jajko kurze powinno wiązać się z rezygnacją z majonezu, niektórych sosów, pieczywa z błyszczącą skórką (efekt ten uzyskiwany jest przez posmarowanie chleba surowym jajkiem przed pieczeniem). Niebezpieczne może być także picie piwa i kawy, do których jajko dodawane jest w celu polepszenia jakości pianki. Alergicy powinni zatem szczególnie dokładnie analizować podany na etykietach skład produktów. Niestety, jaja mogą występować w artykułach spożywczych pod różnymi nazwami. Wśród głównych alergenów jajka kurzego, które stanowią składnik wielu produktów, należą.:  owomukoid, owoalbumina, witelina, owoglobulina, albumina, lipowitelina, globulina. Jajko zawiera szeroką gamę ważnych składników odżywczych. Nie można więc po prostu wyeliminować go z diety, aby nie doprowadzić do niedoboru białka. By zbilansować dietę, jajko można zastąpić piersią kurczaka, tuńczykiem, chudą wieprzowiną. Zaleca się również wprowadzenie do diety lekkiego twarogu, jogurtów. Przed wprowadzeniem diety eliminującej jajka, warto skorzystać z porady dietetyka."},
  {name: "mleko krowie", description: "Alergia na mleko krowie (białka mleka krowiego) jest jak dotąd najczęstszą alergią pokarmową. Najczęściej pojawia się u małych dzieci (rzadziej u dorosłych). Najważniejsze alergeny mleka to kazeina oraz alfa- i beta-laktoglobuliny. Oprócz mleka w czystej formie (tj. prosto od krowy, pasteryzowane, sterylizowane, UHT), alergeny występują też w postaci przetworów, jak: mleka smakowe, jogurty, śmietany, sery, masło, lody, pieczywo cukiernicze, słodycze, sosy, kaszki instant. Dodatki mleka spotyka się też w majonezie, sosach sałatkowych, purée ziemniaczanym, margarynie, naleśnikach, pierogach, zupach w proszku, potrawach w słoikach i puszkach, gotowych daniach, pieczywie (dodatek serwatki o minimalnym działaniu alergizującym). Mleko dodaje się też do wędlin i pasztetów. Znajduje się w potrawach panierowanych, odżywkach dla sportowców, a także w niektórych lekach. Zarówno u niemowlaka, dzieci, jak i u dorosłych pojawiają się objawy na skórze, ze strony układu pokarmowego i oddechowego. W skrajnych przypadkach może dojść do wstrząsu anafilaktycznego."},
  {name: "gluten", description: "Gluten to rodzaj białek (gluteniny i gliadyny) występujących w zbożach, np. pszenicy, życie czy jęczmieniu, który u wielu osób wywołuje reakcje alergiczne. Śladowe ilości glutenu można także spotkać w produktach spożywczych, które z pozoru nie powinny zawierać zbóż, np. w wędlinach, zupach i sosach w proszku, czekoladzie, produktach mięsnych oraz rybnych, a nawet majonezie. Według szacunków uczulenie na gluten może dotyczyć nawet 10-20% osób cierpiących na nietolerancje pokarmowe, a z roku na rok rośnie liczba osób stosujących dietę bezglutenową. Reakcja uczuleniowa na gluten możne występować natychmiastowo lub po czasie (nawet 1-2 dni). U dorosłych alergia na gluten ujawnia się najczęściej pod postacią pokrzywki, obrzęku naczynioruchowego, wstrząsu anafilaktycznego lub biegunki. Ponadto u dorosłych obserwuje się postać alergii na gluten, która występuje jedynie po równoczesnym wysiłku fizycznym. U dzieci alergia na gluten objawia się najczęściej w postaci atopowego zapalenia skóry, rzadziej pojawiają się objawy ze strony układu pokarmowego czy oddechowego, które mogą wystąpić po zjedzeniu niewielkich ilości glutenu. Z alergii na gluten, w przeciwieństwie do celiakii, większość dzieci wyrasta."},
  {name: "orzechy", description: "Alergia na orzechy to nadmierna odpowiedź układu odpornościowego na alergenne składniki orzechów, głównie białek zapasowych. Alergia na orzechy może być poważna w skutkach z powodu częstych reakcji ogólnych, a nawet wstrząsów anafilaktycznych, które zagrażają życiu. Alergia na orzeszki ziemne odpowiedzialna jest za 25% przypadków silnych reakcji po spożyciu pokarmów. Niektóre procesy technologiczne, jak np. prażenie orzeszków, znacząco zwiększają ich właściwości alergenne, a to w tej właśnie formie są one bardzo często spożywane. Często też przy alergii na pyłek brzozy występuje alergia krzyżowa na orzeszki ziemne. W takich przypadkach pojawia się reakcja alergiczna w obrębie jamy ustnej (mrowienie ust, gardła, obrzęk warg i języka, chrypka) po spożyciu orzeszków ziemnych. Alergia na orzechy włoskie, alergia na orzechy laskowe jest w Polsce zdecydowanie częstsza niż uczulenie na orzeszki ziemne. Objawy alergii na orzechy są związane przede wszystkim z układem pokarmowym, ale mogą pojawić się również objawy skórne czy objawy ze strony układu oddechowego. U osób uczulonych na orzechy mogą wystąpić takie objawy  jak: biegunki, wymioty, zespół alergii jamy ustnej, pokrzywka kontaktowa, świąd, napady astmy, obrzęk górnych dróg oddechowych. Stosunkowo często mogą wystąpić reakcje uogólnione, np. wstrząs anafilaktyczny."},
  {name: "seler", description: "Seler należy do częstych alergenów pokarmowych. Szczególnie często alergizuje osoby z nieżytem nosa wywołanym nadwrażliwością na pyłek roślin. Wśród symptomów alergii na seler można wymienić nieżyt nosa, wysypkę, duszności, pokrzywkę, rumień oraz obrzęk Quinckego. W wyjątkowych sytuacjach zjedzenie potrawy z selerem może wywołać wstrząs anafilaktyczny, który stanowi poważne zagrożenie dla życia pacjenta. Jedyną skuteczną metodą leczenia alergii na seler jest wyeliminowanie tego składnika z diety, co może być bardzo trudne, ponieważ jego śladowe ilości mogą kryć się nawet w składzie czekolady."},
  {name: "soja", description: "Soja jest popularną rośliną strączkową, którą wykorzystywana jest w przemyśle spożywczym do produkcji oleju, mleka, margaryny czy soków warzywnych. Alergia na soję jest jedną z odmian alergii pokarmowych. Wywołuje ją komponent białkowy ziarna soi. Objawy alergii na soję nie są specyficzne. Podobne dolegliwości zaobserwować możemy we wszystkich rodzajach alergii pokarmowych. Najczęściej dolegliwości dotyczą układu pokarmowego: brak apetytu lub jego wyraźne zmniejszenie, nudności, wymioty, a także biegunki, uczucie pieczenia w ustach po spożyciu niektórych pokarmów, zaczerwienienie okolicy ust, obrzęk warg i języka. U dzieci, zwłaszcza tych małych, alergia ta może dodatkowo objawić się brakiem należytego przyrostu masy ciała, a także niespokojnym zachowaniem dziecka podczas karmienia i niechęci do jedzenia. Możliwe jest również spowolnienie lub nawet zahamowanie rozwoju dziecka, zarówno fizycznego, jak i psychicznego. Do rzadziej obserwowanych objawów zaliczyć możemy: zmiany skórne, bóle głowy, rozdrażnienie, senność i ciągłe uczucie zmęczenia, objawy ze strony układu oddechowego. Jedynym całkowicie skutecznym sposobem leczenia alergii na soję jest unikanie produktów ją zawierających, czyli stosowanie tak zwanej diety eliminacyjnej. Przestrzeganie takiej diety, czyli całkowite wykluczenie nasion tej rośliny z codziennego jadłospisu, nie jest tak łatwe, jakby mogło się wydawać. Wynika to głównie z tego, że soja jest powszechnie dodawana do wielu produktów spożywczych, co nie zawsze jest zaznaczone na etykiecie z ich składem. Śladowe ilości soi możemy znaleźć w sokach warzywnych, batonach, pieczywie, płatkach śniadaniowych, grysiku, ale też w produktach przeznaczonych dla dzieci – na przykład mlekach i kaszkach."},
  {name: "ryby", description: "Ryby zaliczają się do najczęstszych alergenów pokarmowych, zarówno u dorosłych, jak i u dzieci. Bardzo częste jest uczulenie na wiele rodzajów ryb na raz, choć zdarza się także alergia na pojedynczy gatunek. Reakcje uczuleniowe najczęściej są natychmiastowe, ale u niektórych osób objawy mogą wystąpić później, po ok. 8 godzinach od spożycia. U osób uczulonych na ryby mogą wystąpić takie objawy  jak: zmiany skórne, bóle brzucha, biegunki, wymioty, bóle głowy, zapalenie spojówek, duszność, nieżyt nosa, astma, wstrząs anafilaktyczny. Najczęściej uczulające gatunki ryb to: dorsz, śledź, szprota, węgorz, tuńczyk, łosoś, karp, okoń. Ryby są bogatym źródłem kwasów Omega-3, które mają korzystny wpływ m.in.: na układ sercowo-naczyniowy, mózg, skórę czy stawy. Przy ich eliminacji z diety mogą wystąpić niedobory. Warto więc spożywać inne produkty zawierające kwasy Omega-3, np. nasiona chia (szałwii hiszpańskiej), siemię lniane, orzechy włoskie i migdały."},
  {name: "sezam", description: ""},
  {name: "cukier", description: ""},
  {name: "mięso", description: ""}
])
Brand.create!([
  {name: "Pudliszki"},
  {name: "Kotlin"},
  {name: "Winiary"},
  {name: "Krakus"},
  {name: "Łowicz"},
  {name: "Lubella"},
  {name: "Dawtona"},
  {name: "Polskie Młyny"},
  {name: "Bonduelle"}
])
Ingredient.create!([
  {name: "woda"},
  {name: "sól"},
  {name: "curry"}
])

ProductCategory.create!([
  {name: "pieczywo"},
  {name: "słodycze i przekąski"},
  {name: "nabiał"},
  {name: "mięso i wędliny"},
  {name: "dania gotowe"},
  {name: "przetwory"},
  {name: "przyprawy i sosy"},
  {name: "makaron, ryż, kasza"},
  {name: "artykuły sypkie"},
  {name: "napoje"}
])
